"""External verification of synthesis reports via headless Claude Code.

The local model that generates synthesis reports (synthesis.py) has no
web/literature access -- it's explicitly instructed to flag anything it
can't verify itself as an "Open Question for External Verification"
rather than assert it either way. This module is the other half of that
division of labour: it shells out to `claude -p` (real web search) once
per idea, batching that idea's open questions into a single call, and
writes the findings back into the report.

Uses the CLI (`claude -p`) rather than the Python/TS Agent SDK -- this
is a one-shot per-idea research task with no need for streaming,
conversation continuation, or custom tool callbacks, so the CLI's
`--output-format json --json-schema` is the simplest path to a
structured, parseable result. Deliberately does NOT pass `--bare`: that
would need a separate ANTHROPIC_API_KEY (separate billing from the
user's subscription) for a marginal startup-speed gain that doesn't
matter for a handful of one-shot calls.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

FINDINGS_SCHEMA = {
    "type": "object",
    "properties": {
        "findings": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "question": {"type": "string"},
                    "verdict": {"type": "string", "enum": ["supports", "refutes", "inconclusive"]},
                    "summary": {"type": "string", "description": "2-4 sentences on what real sources say"},
                    "sources": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["question", "verdict", "summary", "sources"],
            },
        },
    },
    "required": ["findings"],
}


def _parse_ideas(report_text: str) -> list[dict]:
    """Split a synthesis report into per-idea blocks and pull out just
    what verification needs: the title, the concept (for context), and
    the open questions list -- reusing the report's own known structure
    (it's generated by synthesis.py, not arbitrary markdown)."""
    ideas = []
    for block in re.split(r"(?m)^## Idea \d+: ", report_text)[1:]:
        title = block.split("\n", 1)[0].strip()
        concept_m = re.search(r"### Proposed Concept\s*\n(.*?)(?=\n### )", block, re.DOTALL)
        oq_m = re.search(
            r"### Open Questions for External Verification\s*\n\*.*?\*\s*\n\n(.*?)(?=\n---|\Z)",
            block, re.DOTALL,
        )
        concept = concept_m.group(1).strip() if concept_m else ""
        questions = []
        if oq_m:
            questions = [
                line.lstrip("-").strip() for line in oq_m.group(1).splitlines()
                if line.strip().startswith("-")
            ]
        if concept and questions:
            ideas.append({"title": title, "concept": concept, "questions": questions})
    return ideas


def _verify_idea(concept: str, questions: list[str]) -> tuple[dict | None, float]:
    """One headless Claude call per idea, batching all its open questions
    together -- a single web-search-capable call costs real money
    (~$0.30-0.80 observed), so batching per-idea rather than per-question
    matters for cost, not just convenience."""
    numbered = "\n".join(f"{i}. {q}" for i, q in enumerate(questions, 1))
    prompt = f"""A speculative idea was proposed by a local LLM analyzing a personal knowledge base for cross-domain connections. It has open questions it could not verify itself (no web access).

IDEA: {concept}

OPEN QUESTIONS:
{numbered}

For each question, search the web for relevant literature or prior art, then report a verdict (supports/refutes/inconclusive, relative to what the idea assumes), a concise summary of what you actually found, and the real source URLs you used. Be honest if search turns up nothing conclusive -- "inconclusive" is a legitimate answer."""

    cmd = [
        "claude", "-p", prompt,
        "--allowedTools", "WebSearch",
        "--permission-mode", "auto",
        "--permission-prompts", "none",
        "--output-format", "json",
        "--json-schema", json.dumps(FINDINGS_SCHEMA),
    ]
    try:
        # encoding must be explicit: without it, subprocess falls back to
        # the locale's default (cp1252 on this machine), which mangles
        # claude -p's UTF-8 stdout into mojibake (real bytes seen in
        # practice: em-dashes and accented characters like "Matérn"
        # corrupted into "â€”" / "MatÃ©rn").
        result = subprocess.run(
            cmd, capture_output=True, text=True, encoding="utf-8", timeout=300, check=False
        )
        data = json.loads(result.stdout)
    except Exception as e:
        print(f"    ! claude -p call failed: {e}", flush=True)
        return None, 0.0
    if data.get("is_error"):
        print(f"    ! claude -p returned an error: {data.get('result')}", flush=True)
        return None, data.get("total_cost_usd", 0.0)
    return data.get("structured_output"), data.get("total_cost_usd", 0.0)


def _render_findings(findings: list[dict]) -> str:
    lines = []
    for f in findings:
        lines.append(f"**Q: {f['question']}**")
        lines.append(f"- Verdict: **{f['verdict']}**")
        lines.append(f"- {f['summary']}")
        if f.get("sources"):
            lines.append("- Sources: " + ", ".join(f["sources"]))
        lines.append("")
    return "\n".join(lines)


def verify_report(report_path: str, max_cost: float = 5.0) -> tuple[Path, float]:
    path = Path(report_path)
    text = path.read_text(encoding="utf-8")
    ideas = _parse_ideas(text)
    if not ideas:
        raise RuntimeError("No ideas with open questions found in this report")

    total_cost = 0.0
    updated = text
    for i, idea in enumerate(ideas, 1):
        if total_cost >= max_cost:
            print(f"  [{i}/{len(ideas)}] Skipping \"{idea['title']}\" -- "
                  f"budget cap (${max_cost:.2f}) reached", flush=True)
            continue
        print(f"  [{i}/{len(ideas)}] Verifying \"{idea['title']}\" "
              f"({len(idea['questions'])} question(s))...", flush=True)
        result, cost = _verify_idea(idea["concept"], idea["questions"])
        total_cost += cost
        print(f"      -> cost: ${cost:.4f} (running total: ${total_cost:.4f})", flush=True)
        if not result or not result.get("findings"):
            print("      ! no usable result, leaving open questions as-is", flush=True)
            continue

        # Anchor on the unique "## Idea N: " heading, not the bare title --
        # every idea's title also appears earlier in the report's own
        # "Summary: open questions" section, so searching for the title
        # alone matches that first (wrong) occurrence, and each
        # subsequent idea's insertion cascades into the previous one's
        # already-inserted block instead of its own section.
        heading = f"## Idea {i}: "
        heading_pos = updated.find(heading)
        if heading_pos == -1:
            continue
        marker = (
            f"### Open Questions for External Verification\n"
            f"*Flagged by the model itself as beyond what it can check without "
            f"web/literature access -- worth researching (e.g. by asking Claude to "
            f"look these up) before treating the idea above as sound.*\n"
        )
        insertion_point = updated.find(marker, heading_pos)
        if insertion_point == -1:
            continue
        section_end = updated.find("\n---", insertion_point)
        if section_end == -1:
            section_end = len(updated)
        verification_block = (
            "\n\n### External Verification Results (via Claude, real web search)\n\n"
            + _render_findings(result["findings"])
        )
        updated = updated[:section_end] + verification_block + updated[section_end:]

    path.write_text(updated, encoding="utf-8")
    return path, total_cost
