"""External verification of synthesis reports via headless Claude Code.

The local model that generates synthesis reports (synthesis.py) has no
web/literature access -- it's explicitly instructed to flag anything it
can't verify itself as an "Open Question for External Verification"
rather than assert it either way. This module is the other half of that
division of labour: it shells out to `claude -p` (real web search) once
per idea, batching that idea's open questions into a single call, and
writes the findings back into the report.

Uses the CLI (`claude -p`) rather than the Python/TS Agent SDK -- this
is a one-shot per-idea research task with no need for streaming,
conversation continuation, or custom tool callbacks, so the CLI's
`--output-format json --json-schema` is the simplest path to a
structured, parseable result. Deliberately does NOT pass `--bare`: that
would need a separate ANTHROPIC_API_KEY (separate billing from the
user's subscription) for a marginal startup-speed gain that doesn't
matter for a handful of one-shot calls.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import time
from pathlib import Path

from . import graph as graph_mod

_MEMSEARCH_DIR = Path(graph_mod.DEFAULT_GRAPH_PATH).parent
VERIFY_CACHE_PATH = _MEMSEARCH_DIR / "verify_cache.json"
SYNTHESIS_INDEX_PATH = _MEMSEARCH_DIR / "synthesis_index.json"
CACHE_MAX_AGE_DAYS = 7

FINDINGS_SCHEMA = {
    "type": "object",
    "properties": {
        "findings": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "question": {"type": "string"},
                    "verdict": {"type": "string", "enum": ["supports", "refutes", "inconclusive"]},
                    "summary": {"type": "string", "description": "2-4 sentences on what real sources say"},
                    "sources": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["question", "verdict", "summary", "sources"],
            },
        },
    },
    "required": ["findings"],
}


def _parse_ideas(report_text: str) -> list[dict]:
    """Split a synthesis report into per-idea blocks and pull out just
    what verification needs: the real idea number (NOT its position in
    the returned list -- see below), the title, the concept (for
    context), and the open questions list -- reusing the report's own
    known structure (it's generated by synthesis.py, not arbitrary
    markdown)."""
    ideas = []
    headings = list(re.finditer(r"(?m)^## Idea (\d+): ", report_text))
    for idx, m in enumerate(headings):
        number = int(m.group(1))
        start = m.end()
        end = headings[idx + 1].start() if idx + 1 < len(headings) else len(report_text)
        block = report_text[start:end]

        # An idea that's already been through a verify pass has its own
        # "### External Verification Results" section further down the
        # same block -- skip it outright rather than re-parsing. Two real
        # bugs would follow from not skipping: the open-questions regex's
        # lookahead (originally just "next --- or end") would run past
        # the "Open Questions" section into the verification results
        # section itself and misread its "- Sources: ..." lines as new
        # questions (caught in practice: a 5-question idea suddenly
        # showing "20 question(s)" on a second run), and even with that
        # regex fixed, the insertion logic below would still append a
        # second, duplicate "External Verification Results" block after
        # the first. Separately: this function used to return a plain
        # list and callers assumed list position == idea number, which
        # breaks the instant any idea is skipped (position 1 in a
        # filtered list is not necessarily "## Idea 1") -- fixed by
        # carrying the real number explicitly in each returned dict.
        if "### External Verification Results" in block:
            continue

        title = block.split("\n", 1)[0].strip()
        concept_m = re.search(r"### Proposed Concept\s*\n(.*?)(?=\n### )", block, re.DOTALL)
        oq_m = re.search(
            r"### Open Questions for External Verification\s*\n\*.*?\*\s*\n\n(.*?)(?=\n---|\n### |\Z)",
            block, re.DOTALL,
        )
        concept = concept_m.group(1).strip() if concept_m else ""
        questions = []
        if oq_m:
            questions = [
                line.lstrip("-").strip() for line in oq_m.group(1).splitlines()
                if line.strip().startswith("-")
            ]
        if concept and questions:
            ideas.append({"number": number, "title": title, "concept": concept, "questions": questions})
    return ideas


def _cache_key(concept: str, questions: list[str]) -> str:
    payload = concept + "\n" + "\n".join(sorted(questions))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _load_json(path: Path) -> dict | list:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def _save_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def _verify_idea(concept: str, questions: list[str], cache: dict) -> tuple[dict | None, float, bool]:
    """One headless Claude call per idea, batching all its open questions
    together -- a single web-search-capable call draws real usage
    (~$0.30-0.80 observed against the subscription allowance), so
    batching per-idea rather than per-question matters for cost, not
    just convenience. Cached by a hash of (concept, questions) for
    CACHE_MAX_AGE_DAYS -- re-running verify on a report that hasn't
    changed (or re-verifying the same open question that recurs across
    ideas) shouldn't repeat the same paid call within that window.
    Returns (result, cost, was_cached)."""
    key = _cache_key(concept, questions)
    cached = cache.get(key)
    if cached and (time.time() - cached["timestamp"]) < CACHE_MAX_AGE_DAYS * 86400:
        return cached["result"], 0.0, True

    numbered = "\n".join(f"{i}. {q}" for i, q in enumerate(questions, 1))
    prompt = f"""A speculative idea was proposed by a local LLM analyzing a personal knowledge base for cross-domain connections. It has open questions it could not verify itself (no web access).

IDEA: {concept}

OPEN QUESTIONS:
{numbered}

For each question, search the web for relevant literature or prior art, then report a verdict (supports/refutes/inconclusive, relative to what the idea assumes), a concise summary of what you actually found, and the real source URLs you used. Be honest if search turns up nothing conclusive -- "inconclusive" is a legitimate answer."""

    cmd = [
        "claude", "-p", prompt,
        "--allowedTools", "WebSearch",
        "--permission-mode", "auto",
        "--permission-prompts", "none",
        "--output-format", "json",
        "--json-schema", json.dumps(FINDINGS_SCHEMA),
    ]
    try:
        # encoding must be explicit: without it, subprocess falls back to
        # the locale's default (cp1252 on this machine), which mangles
        # claude -p's UTF-8 stdout into mojibake (real bytes seen in
        # practice: em-dashes and accented characters like "Matérn"
        # corrupted into "â€”" / "MatÃ©rn").
        result = subprocess.run(
            cmd, capture_output=True, text=True, encoding="utf-8", timeout=300, check=False
        )
        data = json.loads(result.stdout)
    except Exception as e:
        print(f"    ! claude -p call failed: {e}", flush=True)
        return None, 0.0, False
    if data.get("is_error"):
        print(f"    ! claude -p returned an error: {data.get('result')}", flush=True)
        return None, data.get("total_cost_usd", 0.0), False
    output = data.get("structured_output")
    if output:
        cache[key] = {"result": output, "timestamp": time.time()}
    return output, data.get("total_cost_usd", 0.0), False


def _derive_status(findings: list[dict]) -> str:
    """An idea stays "accepted" unless its own verification results
    genuinely undercut it -- any outright "refutes" verdict is enough to
    move it to "needs_review" rather than leaving it looking equally
    ready-to-pursue as an idea whose premise held up. This is a
    deliberately low bar (one refute, not a majority): a single refuted
    load-bearing claim is reason enough to want a second look before
    treating the idea as sound."""
    if any(f.get("verdict") == "refutes" for f in findings):
        return "needs_review"
    return "accepted"


def _render_findings(findings: list[dict]) -> str:
    lines = []
    for f in findings:
        lines.append(f"**Q: {f['question']}**")
        lines.append(f"- Verdict: **{f['verdict']}**")
        lines.append(f"- {f['summary']}")
        if f.get("sources"):
            lines.append("- Sources: " + ", ".join(f["sources"]))
        lines.append("")
    return "\n".join(lines)


def verify_report(report_path: str, max_cost: float = 5.0) -> tuple[Path, float]:
    path = Path(report_path)
    text = path.read_text(encoding="utf-8")
    ideas = _parse_ideas(text)
    if not ideas:
        raise RuntimeError("No ideas with open questions found in this report")

    cache = _load_json(VERIFY_CACHE_PATH)
    if not isinstance(cache, dict):
        cache = {}
    index = _load_json(SYNTHESIS_INDEX_PATH)
    if not isinstance(index, list):
        index = []

    total_cost = 0.0
    updated = text
    for pos, idea in enumerate(ideas, 1):
        n = idea["number"]
        if total_cost >= max_cost:
            print(f"  [{pos}/{len(ideas)}] Skipping Idea {n} \"{idea['title']}\" -- "
                  f"budget cap (${max_cost:.2f}) reached", flush=True)
            continue
        print(f"  [{pos}/{len(ideas)}] Verifying Idea {n} \"{idea['title']}\" "
              f"({len(idea['questions'])} question(s))...", flush=True)
        result, cost, was_cached = _verify_idea(idea["concept"], idea["questions"], cache)
        total_cost += cost
        _save_json(VERIFY_CACHE_PATH, cache)
        cache_note = " (cached, no new API call)" if was_cached else ""
        print(f"      -> cost: ${cost:.4f} (running total: ${total_cost:.4f}){cache_note}", flush=True)
        if not result or not result.get("findings"):
            print("      ! no usable result, leaving open questions as-is", flush=True)
            continue

        # Anchor on the unique "## Idea N: " heading, not the bare title --
        # every idea's title also appears earlier in the report's own
        # "Summary: open questions" section, so searching for the title
        # alone matches that first (wrong) occurrence, and each
        # subsequent idea's insertion cascades into the previous one's
        # already-inserted block instead of its own section.
        heading = f"## Idea {n}: "
        heading_pos = updated.find(heading)
        if heading_pos == -1:
            continue
        marker = (
            f"### Open Questions for External Verification\n"
            f"*Flagged by the model itself as beyond what it can check without "
            f"web/literature access -- worth researching (e.g. by asking Claude to "
            f"look these up) before treating the idea above as sound.*\n"
        )
        insertion_point = updated.find(marker, heading_pos)
        if insertion_point == -1:
            continue
        section_end = updated.find("\n---", insertion_point)
        if section_end == -1:
            section_end = len(updated)
        verification_block = (
            "\n\n### External Verification Results (via Claude, real web search)\n\n"
            + _render_findings(result["findings"])
        )
        updated = updated[:section_end] + verification_block + updated[section_end:]

        new_status = _derive_status(result["findings"])
        verdict_tally: dict[str, int] = {}
        for f in result["findings"]:
            v = f.get("verdict", "inconclusive")
            verdict_tally[v] = verdict_tally.get(v, 0) + 1
        report_name = path.name
        for entry in index:
            if entry.get("report_file") == report_name and entry.get("idea_number") == n:
                if entry.get("status") != new_status:
                    print(f"      -> status: {entry.get('status', 'accepted')} -> {new_status}", flush=True)
                entry["status"] = new_status
                entry["verdicts"] = verdict_tally
                break

    path.write_text(updated, encoding="utf-8")
    _save_json(SYNTHESIS_INDEX_PATH, index)
    return path, total_cost
